### ISSUE TITLE
What does words_used_in_sent mean in model.py?

### ISSUE THREAD

**Issue by hdchao1989** [monikkinom/ner-lstm#11]
In model.py, I don't figure out the function of words_used_in_sent?  Would you explain to me please? Thank U very much!

**Comment by shreenibhar** [comment]
words_used_in_sent = tf.sign(tf.reduce_max(tf.abs(self.input_data), reduction_indices=2))
the input data sentences contains variable sentence lengths. Hence the sentences are 0 padded to fixed length. Basically words_used_in_sent is a variable which transforms None * sentence_size * num_words into  None * sentence_size. NOTE: None is number of sentences or batch size.
So the words_used_in_sent is actually a matrix of 0s and 1s. It is 1 if the word is actually present in the sentence or 0 if it is a 0 padded word.
This is just a hacked tensorflow statement to do just that, if u dont understand clearly try substituting and check.
self.length = tf.cast(tf.reduce_sum(words_used_in_sent, reduction_indices=1), tf.int32)
This statement just reduces the 01 matrix to compute the length of each sentence.
