### ISSUE TITLE
model.py error

### ISSUE THREAD

**Issue by Magumbian** [monikkinom/ner-lstm#12]
Hello guys,

Thank you for the great work

I have been trying to adopt your code to my work but get this error

ValueError: Cannot feed value of shape (128, 40, 207) for Tensor 'Placeholder:0', which has shape '(?, 40, 200)'

I am not an ML guru but have tried to follow the instructions as best I can. What could be the issue?
My embedding size is 200, sentence length is 40 and batch size is 128.

**Comment by shreenibhar** [comment]
The tensor flow code seems correct as it shoes cannot feed value in
?,40,200.
But your embedding size seems wrong as it shows 128, 40, 207.
Try loading the pickle files in python and check it's shape. Verify that it
is 128, 40, 200.
If not then generate the embedding again with size 193. The seven extra
features will add up to 200.
