### ISSUE TITLE
Usage in production

### ISSUE THREAD

**Issue by nitinmeharia** [monikkinom/ner-lstm#15]
How can we use it in production. Lets say I made the model here and stored its object. Now in production when i get user's query, do we have to run tf.Session() 's run every time?

**Comment by monikkinom** [comment]
Yes but that would will not be very efficient. Once you have saved the trained model with the params, you can use https://tensorflow.github.io/serving/ which is Tensorflow's official solution for running models in production. Hope it answers your question.

**Comment by nitinmeharia** [comment]
Thanks mate. I'll read about it.
