### ISSUE TITLE
Doubts in code

### ISSUE THREAD

**Issue by nitinmeharia** [monikkinom/ner-lstm#16]
Hi, I have few doubts in the code, perhaps some of these would be really silly. But I'll really appreciate if someone can explain them.

1. In glove_model.py, what is **vectors.txt**?
```
parser.add_argument('--restore', type=str, default=None, help='pre-trained glove vectors.txt')
```

2. In model.py, what does **class_size** refers to and its implication?
```
parser.add_argument('--class_size', type=int, help='number of classes', required=True)
```

3. What does the following output of model.py imply?
```
[nan, 1.0, nan, nan, 0.90909090909090906, 0.5]
max model saved in file: model_max.ckpt
test_b score:
[nan, 0.40000000000000002, nan, nan, 0.76190476190476197, 0.14814814814814814]
```

4.  In sample.py, what is **input_embed**?
```
parser.add_argument('--input_embed', type=str, help='location of input pickle embedding', required=True)
```

**Comment by shreenibhar** [comment]
1.
vectors.txt the text file which will ultimately contain the result output.
so it is like:
word1 x1 x2 ....... xdim
word2 x1 x2 ....... xdim
....
2.
class_size is the number of classes
so say you have car, plane, cycle.
class size = 3
3.
the scores represent the f1 scores of each class.
the final value is the combined f1 score.
4.
the files generated from glove_vec.py or word_vec.py
