### ISSUE TITLE
Problem with Tensor Flow 0.9

### ISSUE THREAD

**Issue by zero76114** [monikkinom/ner-lstm#2]
@monikkinom 
I get a error when run main.py
ImportError: This module is deprecated.  Use tf.nn.rnn_cell instead.
My version Tensor Flow is 0.9; Do you have any idea to solve that? 
Many thanks

**Comment by shreenibhar** [comment]
As of now we have done it on tensor flow 0.8 because of bidirectional lstm gpu support.
tensor flow 0.9 is not supported in this code as of now.

**Comment by monikkinom** [comment]
The code has been updated and it is compatible with tensorflow 0.9 and above
