### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by AmareshPandey** [monikkinom/ner-lstm#5]
First of all work is great and inspirational with very good results for a Bidirectional LSTM. Thanks for making this available! I know you have written very nice readme file but still, I am finding it little difficult to run it on my local system, specifically generating the train_embed.pkl, train_tag.pkl , test_a_embed.pkl and test_a_tag.pkl file. Your help will be much appreciated if you can help me in generating this embeddings files with sample input text and default parameters.

**Comment by abhinavwalia95** [comment]
You may generate it by running get_conll_embeddings.py. Hope it helps!

**Comment by shreenibhar** [comment]
first get a conll dataset file then input in the get_conll_embeddings.py.
